### ISSUE TITLE
RuntimeError with Ecto 2.0

### ISSUE THREAD

**Issue by webzepter** [antonmi/espec_phoenix#16]
@antonmi I updated ecto to the last version and my espec tests are red now :fearful:
As said in [Ecto changelog](https://github.com/elixir-lang/ecto/blob/v2.0.0-beta.0/CHANGELOG.md), I replaced `begin_test_transaction` with `Ecto.Adapters.SQL.Sandbox.mode(FishDuel.Repo, :manual)` and `restart_test_transaction` with `:ok = Ecto.Adapters.SQL.Sandbox.checkout(FishDuel.Repo)`, but still recieve this error:
```
** (exit) an exception was raised:
    ** (RuntimeError) cannot find ownership process for #PID<0.560.0>. This may happen if you have not explicitly checked out or the checked out process crashed
        (db_connection) lib/db_connection.ex:817: DBConnection.checkout/2
        (db_connection) lib/db_connection.ex:717: DBConnection.run/3
        (db_connection) lib/db_connection.ex:535: DBConnection.prepare_execute/4
        (ecto) lib/ecto/adapters/sql.ex:362: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:122: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/4
        (ecto) lib/ecto/repo/queryable.ex:67: Ecto.Repo.Queryable.one!/4
        (fishduel) web/controllers/payment_method/withdraws_controller.ex:10: FishDuel.PaymentMethod.WithdrawsController.create/2
```

**Comment by pragmaticivan** [comment]
Having the same issue ;/

**Comment by sriedel** [comment]
Using ecto-2.0.0-rc.3 and phoenix-ecto-3.0.0-rc.0 it seems to be working. 

I added to the bottom of spec/phoenix_helper.exs:
    Ecto.Adapters.SQL.Sandbox.mode( App.Repo, :manual )

And in spec/spec_helper.exs:
      config.before fn ->
        :ok = Ecto.Adapters.SQL.Sandbox.checkout( App.Repo )
         {:shared, hello: :world}
       end

       config.finally fn(_shared) ->
          :ok = Ecto.Adapters.SQL.Sandbox.checkin( App.Repo )
          :ok
        end

Seems to be working for me.

**Comment by pragmaticivan** [comment]
@sriedel worked for me too, thanks.

**Comment by antonmi** [comment]
@sriedel thanks for the solution!

**Comment by walter** [comment]
@sriedel your fix did the trick for me as well. Thanks!
