### ISSUE TITLE
Add support for Phoenix channels

### ISSUE THREAD

**Issue by vitalis** [antonmi/espec_phoenix#17]
It will be nice to have support for phoenix channels, @antonmi I can try to issue pull request if you need help

**Comment by antonmi** [comment]
Hi Vitaly!
Yes, sure!
Pull requests are welcomed!
Don't forget add related functionality and specs to test_app

**Comment by antonmi** [comment]
It would be perfect to implement a chat in test_app. You can follow this approach: [Phoenix_chat_example](https://github.com/chrismccord/phoenix_chat_example)

**Comment by col** [comment]
:+1:

**Comment by col** [comment]
@vitalis - Have you started on a pull request for this?

**Comment by brain-geek** [comment]
Channel specs can already be implemented using existing ESpec code, but it's a bit messy. I've posted working implementation [here](https://gist.github.com/brain-geek/144003ccccdd4cfa866f).

If there are suggestions how to change the example, that would be awesome.

**Comment by vitalis** [comment]
@col I'm working on it, will issue a pull request in a few days

**Comment by antonmi** [comment]
Please, look at 0.6.0.

**Comment by vitalis** [comment]
@antonmi Cool! Thank you for adding channels support.
 I see that from version 0.5.0 you removed requests specs support, any specific reason for it? We have a lot of requests specs and now I don't have a way to upgrade from 0.3.0 to 0.6.0 ...

**Comment by antonmi** [comment]
Hi, @vitalis !
According to phoenix conventions, controllers specs plays that role.
Please, take a look at examples in 'rumbrella' project.

**Comment by vitalis** [comment]
Tnx @antonmi, updated my specs to controller specs, everything works great, thank you for the amazing contribution to elixir community!!!!

**Comment by antonmi** [comment]
Thanks for using ESpec
