### ISSUE TITLE
Issue with reading/checking json generated by a controller

### ISSUE THREAD

**Issue by mlankenau** [antonmi/espec_phoenix#25]
Probably not an issue, more a feature request, but...

I try to test a action that is returning json and I see no way doing that. My quick fix is

      result = action(:solve, {"some_params" => "foo"}).resp_body
               |> Poison.decode
               |> case do
                {:ok, data} -> data
               end
      expect(result.solution) |> to(eq  [true, true, false])

There is prabably a better way to do that, but how?

**Comment by facto** [comment]
@mlankenau I just created a new package, [test_that_json_espec](https://github.com/facto/test_that_json_espec), that should hopefully make this easier.

**Comment by antonmi** [comment]
Thanks, @facto!
