### ISSUE TITLE
Test That JSON! ESpec-- add to README?

### ISSUE THREAD

**Issue by facto** [antonmi/espec_phoenix#31]
I just released the initial version of [test_that_json_espec](https://github.com/facto/test_that_json_espec), which provides ESpec matchers for testing JSON.

Right now, the view and request specs are geared more towards HTML.

I'm happy to add to the README some sample usage or even just a link as a suggested package to look into for JSON testing.

Thoughts?

**Comment by antonmi** [comment]
Awesome!
I'm happy to see such extensions.
In the nearest future, I want to change espec_phoenix paradigm to be more lightweight and easy to extend!
So, @facto, you support me on my way!
Thanks!

**Comment by antonmi** [comment]
Please make PR to Readme.
Smth like Extension section.
