### ISSUE TITLE
Obsolete ecto dependency in some cases?

### ISSUE THREAD

**Issue by brain-geek** [antonmi/espec_phoenix#36]
Hey

Right now I have Phoenix app without Ecto. But installing `espec_phoenix` still makes `ecto` required dependency. Is it possible to make this dependency optional somehow?

**Comment by antonmi** [comment]
Hi, Alex!
Seems like both phoenix and echo dependencies can be dev only.
Will check tomorrow

**Comment by brain-geek** [comment]
As for Phoenix - the project is `espec_phoenix`, so dependency on Phoenix is understandable. But removing Ecto dependency could be beneficial.

**Comment by antonmi** [comment]
@brain-geek I've released 0.6.2 which has only espec dependency.

**Comment by facto** [comment]
@antonmi I'm not entirely sure but I think phoenix must remain a dependency because of the use of `Mix.Phoenix`. Please correct me if I am wrong.

**Comment by antonmi** [comment]
@facto , you are right!
Thanks!

**Comment by antonmi** [comment]
I've returned the dependency in 0.6.4
