### ISSUE TITLE
`init` task doesn't create `spec/spec_helper.exs`

### ISSUE THREAD

**Issue by cheerfulstoic** [antonmi/espec_phoenix#47]
Just installed `espec_phoenix` and ran the command from the `README`:

```
MIX_ENV=test mix espec_phoenix.init
```

But it didn't create a `spec/spec_helpers.exs` file (I was able to get one by running `MIX_ENV=test mix espec.init`).  I noticed [this commit](https://github.com/antonmi/espec_phoenix/commit/49e161330b44c642664544b71524a1d1bb43abbd) but maybe it hasn't been released yet (it seems to be newer than the most recent release)?

**Comment by antonmi** [comment]
Hi, @cheerfulstoic !
Sorry for late response.
I've just released '0.6.6'. It should work now.

**Comment by cheerfulstoic** [comment]
Perfect, thanks!
