### ISSUE TITLE
Question: Authentications headers on testing..

### ISSUE THREAD

**Issue by erneestoc** [antonmi/espec_phoenix#7]
How can I send auth header to test secure routes? Another question would be..  Is it possible to use the Phoenix.Token.sign function from the before block to sign users in?

**Comment by erneestoc** [comment]
More documentation on how to test json api's would be much appreciated. Can I help with something?

**Comment by antonmi** [comment]
Excuse me for not having answered.
Did you find a solution?

**Comment by erneestoc** [comment]
Sure, I used Plug.Conn.put_req_header to add the secure token to my test request. It has nothing to do with espec.

**Comment by antonmi** [comment]
:thumbsup:
