### ISSUE TITLE
Update `espec` dependency to `0.7.0`

### ISSUE THREAD

**Issue by jamesotron** [antonmi/espec_phoenix#9]
It'd be super cool to be able to use the latest `espec` with `espec_phoenix`.  Is there a reason this doesn't work?

**Comment by antonmi** [comment]
The only reason I haven't time to do this). Sorry.
Just make pull request)

**Comment by mspanc** [comment]
I think it's already obsolete as espec is already at 0.8.

**Comment by mspanc** [comment]
Please also see my PR https://github.com/antonmi/espec_phoenix/pull/11

**Comment by antonmi** [comment]
espec_phoenix 0.1.7 uses the last version of espec (0.8.1) now.
